// 多长度词库

// 4字母单词（简单模式）
export const WORDS_4 = [
  'able', 'acid', 'aged', 'also', 'area', 'army', 'away', 'baby', 'back', 'ball',
  'band', 'bank', 'base', 'bath', 'bear', 'beat', 'been', 'beer', 'bell', 'belt',
  'best', 'bill', 'bird', 'blow', 'blue', 'boat', 'body', 'bomb', 'bond', 'bone',
  'book', 'boom', 'born', 'boss', 'both', 'bowl', 'burn', 'busy', 'call', 'calm',
  'came', 'camp', 'card', 'care', 'case', 'cash', 'cast', 'cell', 'chat', 'chip',
  'city', 'club', 'coal', 'coat', 'code', 'cold', 'come', 'cook', 'cool', 'cope',
  'copy', 'core', 'cost', 'crew', 'crop', 'dark', 'data', 'date', 'dawn', 'days',
  'dead', 'deal', 'dean', 'dear', 'debt', 'deep', 'deny', 'desk', 'diet', 'dirt',
  'disc', 'disk', 'door', 'dose', 'down', 'draw', 'drew', 'drop', 'drug', 'dual',
  'duke', 'dust', 'duty', 'each', 'earn', 'ease', 'east', 'easy', 'edge', 'else',
  'even', 'ever', 'evil', 'face', 'fact', 'fail', 'fair', 'fall', 'fame', 'farm',
  'fast', 'fate', 'fear', 'feat', 'feed', 'feel', 'feet', 'fell', 'felt', 'file',
  'fill', 'film', 'find', 'fine', 'fire', 'firm', 'fish', 'five', 'flat', 'fled',
  'flew', 'flow', 'folk', 'food', 'foot', 'ford', 'form', 'fort', 'four', 'free',
  'from', 'fuel', 'full', 'fund', 'gain', 'game', 'gang', 'gave', 'gear', 'gene',
  'gift', 'girl', 'give', 'glad', 'goal', 'goes', 'gold', 'golf', 'gone', 'good',
  'gray', 'grew', 'grey', 'grow', 'gulf', 'guys', 'hack', 'hair', 'half', 'hall',
  'hand', 'hang', 'hard', 'harm', 'hate', 'have', 'head', 'hear', 'heat', 'held',
  'hell', 'help', 'here', 'hero', 'hide', 'high', 'hill', 'hint', 'hire', 'hold',
  'hole', 'holy', 'home', 'hope', 'host', 'hour', 'huge', 'hung', 'hunt', 'hurt',
  'idea', 'inch', 'iron', 'item', 'jack', 'jail', 'jane', 'jean', 'jobs', 'john',
  'join', 'joke', 'jump', 'jury', 'just', 'keen', 'keep', 'kent', 'kept', 'kick',
  'kill', 'kind', 'king', 'knee', 'knew', 'know', 'lack', 'lady', 'laid', 'lake',
  'land', 'lane', 'last', 'late', 'lead', 'left', 'lens', 'less', 'life', 'lift',
  'like', 'limb', 'line', 'link', 'list', 'live', 'load', 'loan', 'lock', 'logo',
  'long', 'look', 'lord', 'lose', 'loss', 'lost', 'lots', 'loud', 'love', 'luck',
  'made', 'mail', 'main', 'make', 'male', 'mall', 'many', 'mark', 'mass', 'matt',
  'meal', 'mean', 'meat', 'meet', 'menu', 'mere', 'mike', 'mild', 'mile', 'milk',
  'mill', 'mind', 'mine', 'miss', 'mode', 'mood', 'moon', 'more', 'most', 'move',
  'much', 'must', 'name', 'navy', 'near', 'neck', 'need', 'news', 'next', 'nice',
  'nick', 'nine', 'none', 'noon', 'norm', 'nose', 'note', 'okay', 'once', 'only',
  'onto', 'open', 'oral', 'over', 'pace', 'pack', 'page', 'paid', 'pain', 'pair',
  'pale', 'palm', 'park', 'part', 'pass', 'past', 'path', 'peak', 'pick', 'pier',
  'pile', 'pine', 'pink', 'pipe', 'plan', 'play', 'plot', 'plus', 'poem', 'poet',
  'poll', 'pond', 'pool', 'poor', 'pope', 'port', 'pose', 'post', 'pour', 'pray',
  'pull', 'pure', 'push', 'race', 'rain', 'rank', 'rare', 'rate', 'read', 'real',
  'rear', 'rely', 'rent', 'rest', 'rice', 'rich', 'ride', 'ring', 'rise', 'risk',
  'road', 'rock', 'role', 'roll', 'roof', 'room', 'root', 'rose', 'rule', 'rush',
  'safe', 'said', 'sake', 'sale', 'salt', 'same', 'sand', 'save', 'seat', 'seed',
  'seek', 'seem', 'seen', 'self', 'sell', 'send', 'sent', 'ship', 'shop', 'shot',
  'show', 'shut', 'sick', 'side', 'sign', 'silk', 'site', 'size', 'skin', 'slip',
  'slow', 'snow', 'soft', 'soil', 'sold', 'sole', 'some', 'song', 'soon', 'sort',
  'soul', 'spot', 'star', 'stay', 'step', 'stop', 'such', 'suit', 'sure', 'swim',
  'tail', 'take', 'tale', 'talk', 'tall', 'tank', 'tape', 'task', 'team', 'tear',
  'tech', 'tell', 'tend', 'tent', 'term', 'test', 'text', 'than', 'that', 'them',
  'then', 'they', 'thin', 'this', 'thus', 'tide', 'till', 'time', 'tiny', 'tips',
  'tire', 'told', 'toll', 'tone', 'took', 'tool', 'tops', 'tore', 'torn', 'tour',
  'town', 'trap', 'tree', 'trip', 'true', 'tube', 'tune', 'turn', 'twin', 'type',
  'unit', 'upon', 'used', 'user', 'vary', 'vast', 'verb', 'very', 'vice', 'view',
  'vote', 'wage', 'wait', 'wake', 'walk', 'wall', 'want', 'warm', 'wash', 'wave',
  'ways', 'weak', 'wear', 'week', 'well', 'went', 'were', 'west', 'what', 'when',
  'whom', 'wide', 'wife', 'wild', 'will', 'wind', 'wine', 'wing', 'wire', 'wise',
  'wish', 'with', 'woke', 'wolf', 'wood', 'word', 'wore', 'work', 'worn', 'wrap',
  'yard', 'yeah', 'year', 'your', 'zero', 'zone',
]

// 5字母单词（标准模式）
export const WORDS_5 = [
  // 科技相关
  'react', 'rules', 'input', 'logic', 'state', 'hooks', 'array', 'bytes', 'cache', 'debug',
  'email', 'files', 'graph', 'image', 'json', 'links', 'macro', 'nodes', 'parse', 'query',
  'regex', 'stack', 'token', 'users', 'valid', 'yield', 'zones',

  // 常用单词
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again',
  'agent', 'agree', 'ahead', 'alarm', 'album', 'alert', 'align', 'alike', 'alive', 'allow',
  'alone', 'along', 'alter', 'among', 'angel', 'anger', 'angle', 'angry', 'apart', 'apple',
  'apply', 'arena', 'argue', 'arise', 'armor', 'arrow', 'asset', 'avoid', 'award', 'aware',
  'basic', 'basis', 'beach', 'beast', 'began', 'begin', 'being', 'below', 'bench', 'bible',
  'birth', 'black', 'blade', 'blame', 'blank', 'blast', 'bleed', 'blend', 'bless', 'blind',
  'block', 'blood', 'bloom', 'blown', 'board', 'boast', 'bonus', 'boost', 'booth', 'bound',
  'brain', 'brand', 'brave', 'bread', 'break', 'breed', 'brick', 'bride', 'brief', 'bring',
  'broad', 'broke', 'brown', 'brush', 'build', 'bunch', 'burst', 'buyer', 'cable', 'camel',
  'candy', 'cargo', 'carry', 'catch', 'cause', 'chain', 'chair', 'charm', 'chart', 'chase',
  'cheap', 'check', 'cheek', 'chest', 'chief', 'child', 'chose', 'chunk', 'civic', 'civil',
  'claim', 'class', 'clean', 'clear', 'clerk', 'click', 'cliff', 'climb', 'clock', 'close',
  'cloth', 'cloud', 'coach', 'coast', 'color', 'couch', 'could', 'count', 'court', 'cover',
  'crack', 'craft', 'crash', 'crazy', 'cream', 'crisp', 'cross', 'crowd', 'crown', 'crude',
  'crush', 'curve', 'cycle', 'daily', 'dairy', 'dance', 'dealt', 'death', 'debut', 'decay',
  'delay', 'delta', 'dense', 'depth', 'devil', 'diary', 'dirty', 'doubt', 'dozen', 'draft',
  'drain', 'drama', 'drank', 'drawn', 'dream', 'dress', 'dried', 'drift', 'drill', 'drink',
  'drive', 'drown', 'dying', 'eager', 'early', 'earth', 'eight', 'elder', 'elect', 'elite',
  'empty', 'enemy', 'enjoy', 'enter', 'entry', 'equal', 'error', 'essay', 'event', 'every',
  'exact', 'exist', 'extra', 'faint', 'faith', 'false', 'fault', 'favor', 'feast', 'fiber',
  'field', 'fifth', 'fifty', 'fight', 'final', 'first', 'fixed', 'flame', 'flash', 'fleet',
  'flesh', 'float', 'flock', 'flood', 'floor', 'flour', 'fluid', 'flush', 'focal', 'focus',
  'force', 'forge', 'forth', 'forty', 'forum', 'found', 'frame', 'frank', 'fraud', 'fresh',
  'front', 'frost', 'fruit', 'fully', 'funny', 'giant', 'given', 'glass', 'globe', 'glory',
  'glove', 'goose', 'grace', 'grade', 'grain', 'grand', 'grant', 'grape', 'grasp', 'grass',
  'grave', 'great', 'green', 'greet', 'grief', 'grill', 'gross', 'group', 'grove', 'grown',
  'guard', 'guess', 'guest', 'guide', 'guilt', 'habit', 'happy', 'hardy', 'harsh', 'haven',
  'heart', 'heavy', 'hence', 'hobby', 'honey', 'honor', 'horse', 'hotel', 'house', 'human',
  'humor', 'ideal', 'imply', 'index', 'inner', 'issue', 'jelly', 'jewel', 'joint', 'joker',
  'judge', 'juice', 'jumbo', 'jumpy', 'knife', 'knock', 'known', 'label', 'labor', 'lance',
  'large', 'laser', 'latch', 'later', 'laugh', 'layer', 'learn', 'lease', 'least', 'leave',
  'legal', 'lemon', 'level', 'lever', 'light', 'limit', 'linen', 'liver', 'local', 'lodge',
  'loose', 'lorry', 'loser', 'lover', 'lower', 'loyal', 'lucky', 'lunar', 'lunch', 'lyric',
  'magic', 'major', 'maker', 'manga', 'manor', 'maple', 'march', 'marry', 'marsh', 'match',
  'mayor', 'medal', 'media', 'melon', 'mercy', 'merge', 'merit', 'merry', 'metal', 'meter',
  'midst', 'might', 'minor', 'minus', 'mixed', 'model', 'modem', 'money', 'month', 'moral',
  'motor', 'mount', 'mouse', 'mouth', 'movie', 'music', 'naked', 'nasty', 'naval', 'nerve',
  'never', 'newly', 'night', 'ninth', 'noble', 'noise', 'north', 'notch', 'noted', 'novel',
  'nurse', 'occur', 'ocean', 'offer', 'often', 'olive', 'onion', 'opera', 'orbit', 'order',
  'organ', 'other', 'ought', 'outer', 'owner', 'oxide', 'ozone', 'paint', 'panel', 'panic',
  'paper', 'party', 'pasta', 'paste', 'patch', 'pause', 'peace', 'peach', 'pearl', 'penny',
  'phase', 'phone', 'photo', 'piano', 'piece', 'pilot', 'pinch', 'pitch', 'pizza', 'place',
  'plain', 'plane', 'plant', 'plate', 'plaza', 'plead', 'pleas', 'plenty', 'pluck', 'plumb',
  'point', 'polar', 'porch', 'pound', 'power', 'press', 'price', 'pride', 'prime', 'print',
  'prior', 'prize', 'probe', 'proof', 'proud', 'prove', 'proxy', 'pulse', 'punch', 'pupil',
  'puppy', 'purse', 'queen', 'query', 'quest', 'queue', 'quick', 'quiet', 'quite', 'quote',
  'radar', 'radio', 'raise', 'rally', 'ranch', 'range', 'rapid', 'ratio', 'reach', 'react',
  'ready', 'realm', 'rebel', 'refer', 'relax', 'relay', 'reply', 'rider', 'ridge', 'rifle',
  'right', 'rigid', 'risky', 'rival', 'river', 'roast', 'robot', 'rocky', 'roman', 'roost',
  'round', 'route', 'royal', 'rugby', 'ruler', 'rumor', 'rural', 'sadly', 'saint', 'salad',
  'salon', 'sandy', 'sauce', 'scale', 'scare', 'scene', 'scent', 'scope', 'score', 'scout',
  'scrap', 'seize', 'sense', 'serve', 'setup', 'seven', 'shade', 'shake', 'shall', 'shame',
  'shape', 'share', 'sharp', 'sheep', 'sheer', 'sheet', 'shelf', 'shell', 'shift', 'shine',
  'shirt', 'shock', 'shoot', 'shore', 'short', 'shout', 'shown', 'shrub', 'sight', 'sigma',
  'silly', 'since', 'sixth', 'sixty', 'sized', 'skill', 'skull', 'slave', 'sleep', 'slice',
  'slide', 'slope', 'small', 'smart', 'smell', 'smile', 'smoke', 'snake', 'solar', 'solid',
  'solve', 'sorry', 'sound', 'south', 'space', 'spare', 'spark', 'speak', 'speed', 'spell',
  'spend', 'spice', 'spine', 'split', 'spoke', 'spoon', 'sport', 'spray', 'squad', 'stack',
  'staff', 'stage', 'stair', 'stake', 'stamp', 'stand', 'stark', 'start', 'state', 'steak',
  'steal', 'steam', 'steel', 'steep', 'steer', 'stick', 'stiff', 'still', 'stock', 'stomach',
  'stone', 'stood', 'stool', 'store', 'storm', 'story', 'stove', 'strap', 'straw', 'stray',
  'strip', 'stuck', 'study', 'stuff', 'style', 'sugar', 'suite', 'sunny', 'super', 'surge',
  'swamp', 'swear', 'sweat', 'sweep', 'sweet', 'swell', 'swept', 'swift', 'swing', 'sword',
  'syrup', 'table', 'taste', 'teach', 'teeth', 'tempo', 'tense', 'thank', 'theft', 'their',
  'theme', 'there', 'these', 'thick', 'thief', 'thigh', 'thing', 'think', 'third', 'those',
  'three', 'threw', 'throw', 'thumb', 'tight', 'timer', 'title', 'toast', 'today', 'token',
  'topic', 'total', 'touch', 'tough', 'tower', 'trace', 'track', 'trade', 'trail', 'train',
  'trait', 'trash', 'treat', 'trend', 'trial', 'tribe', 'trick', 'tried', 'truck', 'truly',
  'trunk', 'trust', 'truth', 'twice', 'twist', 'ultra', 'uncle', 'under', 'undue', 'union',
  'unity', 'until', 'upper', 'upset', 'urban', 'usage', 'usual', 'valid', 'value', 'vapor',
  'vault', 'venue', 'verse', 'video', 'virus', 'visit', 'vital', 'vivid', 'vocal', 'voice',
  'voter', 'wagon', 'waist', 'waste', 'watch', 'water', 'weary', 'weigh', 'weird', 'wheat',
  'wheel', 'where', 'which', 'while', 'white', 'whole', 'whose', 'widow', 'width', 'wired',
  'woman', 'women', 'world', 'worry', 'worse', 'worst', 'worth', 'would', 'wound', 'woven',
  'wrath', 'write', 'wrong', 'wrote', 'yield', 'young', 'youth', 'zebra', 'zippy', 'zombie',
]

// 6字母单词（困难模式）
export const WORDS_6 = [
  'accept', 'access', 'accord', 'across', 'action', 'active', 'actual', 'advice', 'advise',
  'affair', 'affect', 'afford', 'afraid', 'agency', 'agenda', 'almost', 'always', 'amount',
  'animal', 'annual', 'answer', 'anyone', 'anyway', 'appeal', 'appear', 'around', 'arrive',
  'artist', 'aspect', 'assess', 'assist', 'assume', 'attack', 'attend', 'august', 'author',
  'avenue', 'backed', 'ballot', 'barely', 'battle', 'beauty', 'became', 'become', 'before',
  'behalf', 'behave', 'behind', 'belief', 'belong', 'beside', 'better', 'beyond', 'bishop',
  'border', 'borrow', 'bottle', 'bottom', 'bought', 'bounce', 'branch', 'breath', 'bridge',
  'bright', 'broken', 'bronze', 'budget', 'burden', 'bureau', 'button', 'camera', 'campus',
  'cancer', 'candle', 'canvas', 'carbon', 'career', 'castle', 'cattle', 'caught', 'center',
  'centre', 'chance', 'change', 'charge', 'cheese', 'choice', 'choose', 'chosen', 'church',
  'circle', 'client', 'closed', 'closer', 'coffee', 'column', 'combat', 'coming', 'commit',
  'common', 'comply', 'corner', 'costly', 'county', 'couple', 'course', 'cousin', 'create',
  'credit', 'crisis', 'custom', 'damage', 'dancer', 'danger', 'dealer', 'debate', 'decade',
  'decent', 'decide', 'defeat', 'defend', 'define', 'degree', 'demand', 'depend', 'deploy',
  'deputy', 'desert', 'design', 'desire', 'detail', 'detect', 'device', 'differ', 'dinner',
  'direct', 'doctor', 'dollar', 'domain', 'double', 'driven', 'driver', 'during', 'easily',
  'eating', 'editor', 'effect', 'effort', 'either', 'eleven', 'emerge', 'empire', 'employ',
  'enable', 'ending', 'energy', 'engage', 'engine', 'enough', 'ensure', 'entire', 'entity',
  'equity', 'escape', 'estate', 'ethnic', 'exceed', 'except', 'excuse', 'expand', 'expect',
  'expert', 'export', 'extend', 'extent', 'fabric', 'facing', 'factor', 'fairly', 'fallen',
  'family', 'famous', 'farmer', 'father', 'fellow', 'female', 'figure', 'filing', 'finger',
  'finish', 'fiscal', 'flight', 'flower', 'flying', 'follow', 'forced', 'forest', 'forget',
  'formal', 'format', 'former', 'foster', 'fought', 'fourth', 'freely', 'freeze', 'french',
  'friend', 'frozen', 'future', 'garden', 'gather', 'gender', 'german', 'global', 'golden',
  'gotten', 'ground', 'growth', 'guilty', 'guitar', 'handle', 'happen', 'harbor', 'hardly',
  'hazard', 'headed', 'header', 'health', 'heaven', 'height', 'hidden', 'higher', 'honest',
  'horror', 'hosted', 'hunter', 'ignore', 'impact', 'import', 'impose', 'income', 'indeed',
  'injury', 'inside', 'insist', 'intact', 'intend', 'intent', 'invest', 'island', 'itself',
  'jacket', 'jersey', 'joseph', 'junior', 'killer', 'labour', 'laptop', 'latter', 'launch',
  'lawyer', 'leader', 'league', 'length', 'lesson', 'letter', 'likely', 'lineup', 'liquid',
  'listen', 'little', 'living', 'locate', 'locked', 'london', 'lonely', 'longer', 'losing',
  'lovely', 'lowest', 'luxury', 'mainly', 'makeup', 'manage', 'manner', 'manual', 'margin',
  'marine', 'marker', 'market', 'master', 'matter', 'medium', 'member', 'memory', 'mental',
  'mentor', 'merely', 'merger', 'method', 'middle', 'miller', 'minute', 'mirror', 'mobile',
  'modern', 'modest', 'modify', 'moment', 'monkey', 'mortar', 'mostly', 'mother', 'motion',
  'motive', 'moving', 'murder', 'muscle', 'museum', 'muslim', 'mutual', 'myself', 'narrow',
  'nation', 'native', 'nature', 'nearby', 'nearly', 'neatly', 'needle', 'neural', 'nobody',
  'normal', 'notice', 'notion', 'number', 'object', 'obtain', 'occupy', 'office', 'offset',
  'online', 'option', 'orange', 'origin', 'output', 'palace', 'parent', 'partly', 'patent',
  'patrol', 'patron', 'pencil', 'people', 'period', 'permit', 'person', 'phrase', 'picked',
  'planet', 'player', 'please', 'plenty', 'pocket', 'poetry', 'police', 'policy', 'polish',
  'pollut', 'portal', 'poster', 'potato', 'potter', 'powder', 'praise', 'prayer', 'prefer',
  'pretty', 'priest', 'prince', 'prison', 'profit', 'proper', 'proven', 'public', 'purple',
  'pursue', 'puzzle', 'rabbit', 'racial', 'racing', 'radial', 'random', 'rather', 'rating',
  'reader', 'really', 'reason', 'recall', 'recent', 'record', 'reduce', 'reform', 'refuge',
  'refuse', 'regard', 'region', 'regret', 'reject', 'relate', 'relief', 'remain', 'remark',
  'remedy', 'remind', 'remote', 'remove', 'render', 'repair', 'repeat', 'replay', 'report',
  'rescue', 'resign', 'resist', 'resort', 'result', 'retail', 'retain', 'retire', 'return',
  'reveal', 'review', 'revise', 'reward', 'rhythm', 'riding', 'rising', 'robust', 'rocket',
  'rubber', 'ruling', 'runner', 'safety', 'salary', 'sample', 'saving', 'scheme', 'school',
  'screen', 'script', 'search', 'season', 'second', 'secret', 'sector', 'secure', 'seeing',
  'select', 'seller', 'senate', 'senior', 'series', 'server', 'settle', 'severe', 'shadow',
  'shaped', 'shared', 'shield', 'shorts', 'should', 'shower', 'signal', 'signed', 'silent',
  'silver', 'simple', 'simply', 'singer', 'single', 'sister', 'slight', 'smooth', 'soccer',
  'social', 'sodium', 'solely', 'solved', 'source', 'soviet', 'speech', 'sphere', 'spider',
  'spirit', 'splash', 'spoken', 'spread', 'spring', 'square', 'stable', 'status', 'steady',
  'stereo', 'sticky', 'stolen', 'strain', 'strand', 'stream', 'street', 'stress', 'strict',
  'strike', 'string', 'strong', 'struck', 'studio', 'stupid', 'submit', 'suburb', 'sudden',
  'suffer', 'summer', 'summit', 'sunday', 'supply', 'surely', 'survey', 'switch', 'symbol',
  'system', 'tablet', 'tackle', 'taking', 'talent', 'target', 'tender', 'tennis', 'thanks',
  'theory', 'thirty', 'thread', 'threat', 'thrill', 'thrive', 'thrown', 'ticket', 'tighten',
  'timber', 'timing', 'tissue', 'toggle', 'tomato', 'tongue', 'toolbar', 'topped', 'toward',
  'trader', 'travel', 'treaty', 'tribal', 'tricky', 'triple', 'troops', 'trophy', 'trying',
  'tunnel', 'turkey', 'turned', 'turtle', 'twelve', 'twenty', 'unable', 'unfair', 'unique',
  'united', 'unless', 'unlike', 'update', 'upload', 'useful', 'valley', 'varied', 'vendor',
  'verify', 'versus', 'victim', 'victory', 'viewer', 'virgin', 'virtue', 'vision', 'visual',
  'volume', 'walker', 'wallet', 'warmth', 'wealth', 'weapon', 'weekly', 'weight', 'welfare',
  'wheels', 'whilst', 'wholly', 'widely', 'wilson', 'window', 'winner', 'winter', 'wisdom',
  'within', 'wonder', 'wooden', 'worker', 'worthy', 'wright', 'writer', 'yellow', 'zombie',
]

// 根据长度获取词库
export function getWordsByLength(length: 4 | 5 | 6): string[] {
  switch (length) {
    case 4:
      return WORDS_4
    case 5:
      return WORDS_5
    case 6:
      return WORDS_6
    default:
      return WORDS_5
  }
}

// 验证单词
export function isValidWord(word: string, length: 4 | 5 | 6): boolean {
  const words = getWordsByLength(length)
  return words.includes(word.toLowerCase())
}

// 获取随机单词
export function getRandomWordByLength(length: 4 | 5 | 6): string {
  const words = getWordsByLength(length)
  return words[Math.floor(Math.random() * words.length)]
}
